# Generated by Django 4.2.6 on 2023-10-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Este campo precisa estar marcado para que a página seja exibida publicamente.'),
        ),
    ]
